### ISSUE TITLE
[BUG] Issue data not available after the first analysis on the API with sample page scenario

### ISSUE THREAD

**Issue by rromannissen** [windup/windup-api#24]
**Describe the bug**

When executing the API with sample page scenario, if another application is analyzed after a first analysis, no issue data is obtained.

**To Reproduce**

1. Analyze the customers-tomcat application with the following configuration:

![Screenshot from 2021-11-25 19-05-45](https://user-images.githubusercontent.com/15966456/143486271-5c8d6395-cb90-4479-8fff-026df553f259.png)

2. Application gets analyzed properly, Analysis #1637862073404 is executed and the correct list of issues is displayed when clicking on "Issues"
3. Execute the analysis again by clicking on "Request analysis with custom configuration" with the prefilled data,
4. Analysis #1637862220674 gets executed. Clicking in the "Issues" button displays an empty list:

![Screenshot from 2021-11-25 18-45-34](https://user-images.githubusercontent.com/15966456/143486589-a155f2e6-8bf5-40cd-be5b-2d8297f3d659.png)

![Screenshot from 2021-11-25 18-45-58](https://user-images.githubusercontent.com/15966456/143486612-641d36a5-30fc-49f6-91e2-76829533482d.png)

5. Clicking on the "Issues" button for analysis #1637862073404 still provides the correct issue data though:

![Screenshot from 2021-11-25 18-45-45](https://user-images.githubusercontent.com/15966456/143486695-d7d15444-dda4-4ef1-9a63-d563a3beaf42.png)

6. Refresh the browser, just in case this might be some problem with the browser state. Configuration is kept from the previous analysis. Click on "Request analysis with custom configuration" again.
7. Analysis #1637862389359 is executed:

![Screenshot from 2021-11-25 18-47-14](https://user-images.githubusercontent.com/15966456/143486955-95ede5fe-bc94-4f73-bc69-a2957a963154.png)

8. Clicking in the "Issues" button provides an empty list again:

![Screenshot from 2021-11-25 18-47-21](https://user-images.githubusercontent.com/15966456/143487026-2047df82-db53-48d5-a2fc-650a611a902f.png)

9. Try with another browser, just in case this might be related somehow to some browser status/session problem. Enter the same application and configuration and click on "Request analysis with custom configuration".
10. Analysis #1637862519483 is executed:

![Screenshot from 2021-11-25 18-49-46](https://user-images.githubusercontent.com/15966456/143487296-3cdb5946-71f7-4a10-ba2c-07f07f71cdb6.png)

11. Clicking in the "Issues" button provides an empty list again:

![Screenshot from 2021-11-25 18-49-52](https://user-images.githubusercontent.com/15966456/143487349-bf1868ae-988a-4a41-b0df-a06a745fd674.png)

12. Open the application in an Incognito window. Just in case this is a problem with analyzing the same application several times, a new analysis is configured based on the jee-example-app-1.0.0.ear demo aplication. With that, Analysis #1637863145497 is executed:

![Screenshot from 2021-11-25 19-00-06](https://user-images.githubusercontent.com/15966456/143487515-bcc65d49-c01c-45d1-a79f-5209ac199af0.png)

13. Clicking in the "Issues" button provides an empty list again:

![Screenshot from 2021-11-25 19-00-14](https://user-images.githubusercontent.com/15966456/143487676-43d4457c-3f7c-4098-9963-f6d732e02a9f.png)

**Expected behavior**

Issue data is retained between executions

**Screenshots**

Provided inline

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser Firefox 94.0 from 1 to 8. Chrome 95.0.4638.69 from 9 to 13.
- minikube version: v1.24.0

**Additional context**

None

**Comment by rromannissen** [comment]
I see the bug has been closed. What's the root cause for this? Has it been fixed?

**Comment by mrizzi** [comment]
Yeah, if has been fixed.
I reported in the PR's description a brief explanation of the issue with is a feature in the end and the designed behavior.
I merged to build a newer version of the container so that you can test again following https://github.com/windup/windup-api#api-with-sample-page.
Make me know how it works for you.

**Comment by rromannissen** [comment]
I tested it with several applications and works as expected now. Thanks!
